project_id = "cuvhtdtkuwewslozddfw"

[functions.ifood-sync]
verify_jwt = false

[functions.ifood-webhook]
verify_jwt = false

[functions.food99-webhook]
verify_jwt = false

[functions.keeta-webhook]
verify_jwt = false

[functions.open-delivery-sync]
verify_jwt = false

[functions.open-delivery-dispatch-confirm]
verify_jwt = false

